/**
 * Vanilla docs: list of component slugs and titles for the index page.
 * Each component has its own page at src/pages/docs/vanilla/components/[name].astro.
 */

/** Alphabetical by display title (Accordion … Tooltip) */
export const VANILLA_COMPONENT_SLUGS = [
  'accordion',
  'alert',
  'alert-dialog',
  'aspect-ratio',
  'avatar',
  'back-to-top',
  'badge',
  'breadcrumb',
  'button',
  'button-group',
  'cards',
  'collapsible',
  'context-menu',
  'copy-to-clipboard',
  'dashboard',
  'docs-sidebar',
  'divider',
  'dropdown',
  'empty',
  'footer',
  'font-switcher',
  'forms',
  'hover-card',
  'icons',
  'kbd',
  'label',
  'modal',
  'navbar',
  'pagination',
  'popover',
  'progress-bar',
  'resizable',
  'scroll-area',
  'search',
  'separator',
  'settings',
  'sheet',
  'skeleton',
  'slider',
  'sound-effects',
  'spinner',
  'switch',
  'table',
  'tabs',
  'theme-switcher',
  'toast',
  'toggle',
  'toggle-group',
  'tooltip',
] as const;

export const VANILLA_COMPONENT_TITLES: Record<string, string> = {
  accordion: 'Accordion',
  alert: 'Alert',
  'alert-dialog': 'Alert Dialog',
  'aspect-ratio': 'Aspect Ratio',
  avatar: 'Avatar',
  'back-to-top': 'Back to Top',
  badge: 'Badge',
  breadcrumb: 'Breadcrumb',
  button: 'Button',
  'button-group': 'Button Group',
  cards: 'Cards',
  collapsible: 'Collapsible',
  'context-menu': 'Context Menu',
  'copy-to-clipboard': 'Copy to Clipboard',
  dashboard: 'Dashboard',
  'docs-sidebar': 'Docs Sidebar',
  divider: 'Divider',
  dropdown: 'Dropdown',
  empty: 'Empty',
  footer: 'Footer',
  'font-switcher': 'Font Switcher',
  forms: 'Forms',
  'hover-card': 'Hover Card',
  icons: 'Icons',
  kbd: 'Kbd',
  label: 'Label',
  modal: 'Modal',
  navbar: 'Navbar',
  pagination: 'Pagination',
  popover: 'Popover',
  'progress-bar': 'Progress Bar',
  resizable: 'Resizable',
  'scroll-area': 'Scroll Area',
  search: 'Search',
  separator: 'Separator',
  settings: 'Settings',
  sheet: 'Sheet',
  skeleton: 'Skeleton',
  slider: 'Slider',
  'sound-effects': 'Sound Effects',
  spinner: 'Spinner',
  switch: 'Switch',
  table: 'Table',
  tabs: 'Tabs',
  'theme-switcher': 'Theme Switcher',
  toast: 'Toast',
  toggle: 'Toggle',
  'toggle-group': 'Toggle Group',
  tooltip: 'Tooltip',
};
