/**
 * Vanilla docs: list of component slugs and titles for the index page.
 * Each component has its own page at src/pages/docs/vanilla/components/[name].astro.
 */

export const VANILLA_COMPONENT_SLUGS = [
  'navbar',
  'settings',
  'theme-switcher',
  'button',
  'badge',
  'accordion',
  'breadcrumb',
  'pagination',
  'progress-bar',
  'spinner',
  'avatar',
  'divider',
  'table',
  'icons',
  'copy-to-clipboard',
  'forms',
  'cards',
  'modal',
  'alert',
  'toast',
  'search',
  'tooltip',
  'dropdown',
  'tabs',
] as const;

export const VANILLA_COMPONENT_TITLES: Record<string, string> = {
  navbar: 'Navbar',
  settings: 'Settings',
  'theme-switcher': 'Theme Switcher',
  button: 'Button',
  badge: 'Badge',
  accordion: 'Accordion',
  breadcrumb: 'Breadcrumb',
  pagination: 'Pagination',
  'progress-bar': 'Progress Bar',
  spinner: 'Spinner',
  avatar: 'Avatar',
  divider: 'Divider',
  table: 'Table',
  icons: 'Icons',
  'copy-to-clipboard': 'Copy to Clipboard',
  forms: 'Forms',
  cards: 'Cards',
  modal: 'Modal',
  alert: 'Alert',
  toast: 'Toast',
  search: 'Search',
  tooltip: 'Tooltip',
  dropdown: 'Dropdown',
  tabs: 'Tabs',
};
