/**
 * Vanilla docs: list of component slugs and titles for the index page.
 * Each component has its own page at src/pages/docs/vanilla/components/[name].astro.
 */

/** Alphabetical by display title (Accordion … Tooltip) */
export const VANILLA_COMPONENT_SLUGS = [
  'accordion',
  'alert',
  'avatar',
  'back-to-top',
  'badge',
  'breadcrumb',
  'button',
  'cards',
  'copy-to-clipboard',
  'docs-sidebar',
  'divider',
  'dropdown',
  'footer',
  'font-switcher',
  'forms',
  'icons',
  'modal',
  'navbar',
  'pagination',
  'progress-bar',
  'search',
  'settings',
  'sound-effects',
  'spinner',
  'table',
  'tabs',
  'theme-switcher',
  'toast',
  'tooltip',
] as const;

export const VANILLA_COMPONENT_TITLES: Record<string, string> = {
  accordion: 'Accordion',
  alert: 'Alert',
  avatar: 'Avatar',
  'back-to-top': 'Back to Top',
  badge: 'Badge',
  breadcrumb: 'Breadcrumb',
  button: 'Button',
  cards: 'Cards',
  'copy-to-clipboard': 'Copy to Clipboard',
  'docs-sidebar': 'Docs Sidebar',
  divider: 'Divider',
  dropdown: 'Dropdown',
  footer: 'Footer',
  'font-switcher': 'Font Switcher',
  forms: 'Forms',
  icons: 'Icons',
  modal: 'Modal',
  navbar: 'Navbar',
  pagination: 'Pagination',
  'progress-bar': 'Progress Bar',
  search: 'Search',
  settings: 'Settings',
  'sound-effects': 'Sound Effects',
  spinner: 'Spinner',
  table: 'Table',
  tabs: 'Tabs',
  'theme-switcher': 'Theme Switcher',
  toast: 'Toast',
  tooltip: 'Tooltip',
};
