#!/usr/bin/env node
/**
 * Export design tokens to consumable JSON and JS for design tools and runtimes.
 * Reads ai/design-tokens.json and writes public/tokens/rizzo-tokens.json and .js.
 * Run: node scripts/export-tokens.mjs (or pnpm export:tokens)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const inputPath = join(root, 'ai/design-tokens.json');
const outDir = join(root, 'public/tokens');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

const raw = JSON.parse(readFileSync(inputPath, 'utf8'));
const { _note, ...globalTokens } = raw;

const exportPayload = {
  name: 'rizzo-css',
  version: pkg.version,
  description: 'Design tokens for Rizzo CSS. Use with design tools or runtimes.',
  source: 'ai/design-tokens.json',
  semantic: 'Theme CSS uses --background, --text, --accent, --border, etc. See theme files.',
  tokens: globalTokens,
};

mkdirSync(outDir, { recursive: true });

const jsonPath = join(outDir, 'rizzo-tokens.json');
writeFileSync(jsonPath, JSON.stringify(exportPayload, null, 2), 'utf8');
console.log('Wrote', jsonPath);

const jsContent = `/** Rizzo CSS design tokens - generated by scripts/export-tokens.mjs */
export const rizzoTokens = ${JSON.stringify(exportPayload, null, 2)};
export default rizzoTokens;
`;
const jsPath = join(outDir, 'rizzo-tokens.js');
writeFileSync(jsPath, jsContent, 'utf8');
console.log('Wrote', jsPath);
